# ChairLift Configuration
# This file controls which preference groups are shown in the application
# Set "enabled: false" to hide a preference group on any page

system_page:
  system_info_group:
    enabled: true
  nbc_status_group:
    enabled: true
  health_group:
    enabled: true
    app_id: io.missioncenter.MissionCenter

updates_page:
  updates_status_group:
    enabled: true
    actions:
      - title: Check for System Updates
        script: /usr/bin/bootc upgrade
        sudo: true
  flatpak_updates_group:
    enabled: true
  brew_updates_group:
    enabled: true
  updates_settings_group:
    enabled: true

applications_page:
  applications_installed_group:
    enabled: true
    app_id: io.github.kolunmi.Bazaar
  flatpak_user_group:
    enabled: true
  flatpak_system_group:
    enabled: true
  snap_group:
    enabled: true
  brew_group:
    enabled: true
  brew_search_group:
    enabled: true
  brew_bundles_group:
    enabled: true
    bundles_paths:
      - /usr/share/snow/bundles

maintenance_page:
  maintenance_cleanup_group:
    enabled: false
    actions:
      - title: Clean Up Boot Old Entries
        script: /usr/libexec/bls-gc
        sudo: true
  maintenance_brew_group:
    enabled: true
  maintenance_flatpak_group:
    enabled: true
  maintenance_optimization_group:
    enabled: true

extensions_page:
  installed_group:
    enabled: true
  discover_group:
    enabled: true

help_page:
  help_resources_group:
    enabled: true
    website: https://github.com/frostyard/snow
    issues: https://github.com/frostyard/snow/issues
    chat: https://github.com/frostyard/snow/discussions
